### ISSUE TITLE
强制写入128KBflash的指令

### ISSUE THREAD

**Issue by OliverKung** [wuxx/openocd-toolbox#6]
https://zhuanlan.zhihu.com/p/72752458
在这个帖子中您提到了可以强制刷入后64kbflash
但是似乎现在发布的代码当中并没有这部分的功能
想问下如何处理能实现呢?

**Comment by wuxx** [comment]
可以直接用脚本flash_write.bat烧录，你可以做一个128KB的镜像试试看
